### ISSUE TITLE
[Add new CEFI resource]: NOAA Fisheries Integrated Toolbox

### ISSUE THREAD

**Issue by CathySmithNOAA** [NOAA-PSL/CEFI-info-hub-list#108]
### What is the best title for the data/resource?

NOAA Fisheries Integrated Toolbox

### What is URL that links to data/resource?

https://www.fisheries.noaa.gov/resource/tool-app/noaa-fisheries-integrated-toolbox

### Contact Details

cathy.smith@noaa.gov

### Tell us a bit about the data/resource!

The NOAA Fisheries Integrated Toolbox (NOAA FIT, http://noaa-fisheries-integrated-toolbox.github.io/ ) is a software portal designed to make modeling and analysis tools more readily available to NOAA Fisheries staff. The goal of the NOAA FIT is to ensure that the best available science is used to support the management of living marine resources. The NOAA FIT offers open-source tools that NOAA Fisheries staff use and develop to support open science workflows for research and operations. The portal also includes resources to help NOAA Fisheries scientists and developers create reliable and shareable software.

### Provide a representative figure that relates to the data/resource!

<img width="698" alt="toolbox" src="https://github.com/NOAA-PSL/CEFI-info-hub-list/assets/29237364/e706d106-3365-4d7e-8fcf-3af475e8cc25">

### Dataset

0-Any

### Time Scale

0-Any

### Variables

0-Any

### Product Types

12-Code Repository, 17-Analysis Tools

### Topics

0-Any

### Observing Platforms

0-Any

### Regions

0-Any

### Organizations

14-NOAA Fisheries

**Comment by chiaweh2** [comment]
@CathySmithNOAA thank you for the PR!
