### ISSUE TITLE
GHA to read new resource issues and add to json

### ISSUE THREAD

**Issue by MathewBiddle** [NOAA-PSL/CEFI-info-hub-list#13]
If we really want to automate the whole thing, we can create another GHA that kicks off when a [new issue is created](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment) (with a specific label). The action could then:
1. create a branch to work in
2. read the issue (https://github.com/marketplace/actions/issue-body-parser)
3. parse the contents into the json source file
4. `git add`, `git commit`
5. Finally, submit a PR for manual review https://github.com/marketplace/actions/create-pull-request

Or, we can work through additions as we receive them.

**Comment by chiaweh2** [comment]
Thank you for the great idea! Yes, this certainly sound like a good way to automate things. But I think this would somehow remove the part that allow some discussion or room for discussion in the issue before submitting a PR. I guess through this way the discussion would be mainly in the PR?

**Comment by chiaweh2** [comment]
The GHA is in place and will be triggered when labeling the issue with new resource tag. This create an edit and discussion opportunity in the submitted issue before PR is created. Also accommodate the situation of multiple issue is opened based on the main branch. The strategy is to add one resource at a time and label the next issue which based on the "new base branch"
