### ISSUE TITLE
Add pre-commit check on urls

### ISSUE THREAD

**Issue by MathewBiddle** [NOAA-PSL/CEFI-info-hub-list#50]
it might be a little more overhead but we should add a pre-commit check that all the url's aren't broken.

something as simple as this could work: https://gist.github.com/MathewBiddle/839be6f42b078c5322a8e3eae907de2e

already found https://www.integratedecosystemassessment.noaa.gov/regions/california-current/california-current-marine-heatwave-tracker-blobtracker is broken...

**Comment by chiaweh2** [comment]
looks like the https://www.integratedecosystemassessment.noaa.gov/regions/california-current/california-current-marine-heatwave-tracker-blobtracker is back online?
